language: objective-c
osx_image: beta-xcode6.2

before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool
  - python tools/fixSubmodules.py
  - git submodule update --init --recursive

script:
  ./check.py build
